name: flutball
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.4
  get_it: ^7.2.0
  equatable: ^2.0.3
  retrofit: ^2.2.0
  logger: 1.1.0  #for logging purpose
  flutter_bloc: ^8.0.1
  dartx: ^1.0.0
  dio_http_cache: ^0.3.0
  json_annotation: ^4.1.0
  flutter_svg: ^1.0.3
  dio: 4.0.4
  path: ^1.8.0
  bloc: ^8.0.3
  meta: ^1.7.0
  i18n:
    path: i18n


dev_dependencies:
  retrofit_generator: ^2.0.1
  build_runner: ^2.1.7
  json_serializable: ^4.1.4
  lints: ^1.0.1
  pedantic_mono: any
  mockito: 5.0.15
  golden_toolkit: ^0.13.0
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  bloc_test: ^9.0.1
  flutter_lints: ^1.0.4

dependency_overrides:
  analyzer: 1.7.2 # fix dio http cache

flutter:
  uses-material-design: true
  assets:
    - assets/svg/

