// Mocks generated by Mockito 5.0.15 from annotations
// in flutball/test/domain/usecases/get_match_usecase_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:flutball/core/params/competition_request_params.dart' as _i10;
import 'package:flutball/core/params/match_request_params.dart' as _i6;
import 'package:flutball/core/params/team_request_params.dart' as _i8;
import 'package:flutball/core/resources/data_state.dart' as _i2;
import 'package:flutball/data/repositories/football_repository.dart' as _i3;
import 'package:flutball/domain/entities/competition.dart' as _i9;
import 'package:flutball/domain/entities/match.dart' as _i5;
import 'package:flutball/domain/entities/team.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeDataState_0<T> extends _i1.Fake implements _i2.DataState<T> {}

/// A class which mocks [FootballRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockFootballRepository extends _i1.Mock
    implements _i3.FootballRepository {
  MockFootballRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.DataState<List<_i5.Match>>> getMatches(
          _i6.MatchRequestParams? params) =>
      (super.noSuchMethod(Invocation.method(#getMatches, [params]),
              returnValue: Future<_i2.DataState<List<_i5.Match>>>.value(
                  _FakeDataState_0<List<_i5.Match>>()))
          as _i4.Future<_i2.DataState<List<_i5.Match>>>);
  @override
  _i4.Future<_i2.DataState<_i7.Team>> getTeams(_i8.TeamRequestParams? params) =>
      (super.noSuchMethod(Invocation.method(#getTeams, [params]),
              returnValue: Future<_i2.DataState<_i7.Team>>.value(
                  _FakeDataState_0<_i7.Team>()))
          as _i4.Future<_i2.DataState<_i7.Team>>);
  @override
  _i4.Future<_i2.DataState<List<_i9.Competition>?>> getCompetitions(
          _i10.CompetitionsRequestParams? params) =>
      (super.noSuchMethod(Invocation.method(#getCompetitions, [params]),
              returnValue: Future<_i2.DataState<List<_i9.Competition>?>>.value(
                  _FakeDataState_0<List<_i9.Competition>?>()))
          as _i4.Future<_i2.DataState<List<_i9.Competition>?>>);
  @override
  String toString() => super.toString();
}
