# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Flutter

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '2.10.3'
    - run: flutter pub get
    - name: Run tests
      run: flutter test --coverage
    - name: Install lcov
      run: sudo apt-get install -y lcov
    - name: Remove generated files from code coverage report and entities / models /!\
      run: lcov --remove coverage/lcov.info 'lib/**.gr.dart' 'lib/**.g.dart' 'lib/**.g.dart' 'lib/**/**/**/*.g.dart' 'lib/data/models/*' 'lib/domain/entities/*' -o coverage/lcov.info
    - name: Upload coverage to Codecov
      uses: codecov/codecov-actions@v1.2.1
      with:
        file: coverage/lcov.info
    - name: Build APK
      run: flutter build apk
    - name: Build AppBundle
      run: flutter build appbundle
